name: video_player_web_shaka
description: Web platform implementation of video_player and supports shaka on chrome and other browsers.
homepage: https://github.com/AR-CADE/video_player_web_shaka
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 1.1.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPluginShaka
        fileName: video_player_web_shaka.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.0
  js: ^0.6.7
  video_player_platform_interface: ">=6.2.1 <7.0.0"

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.2 <=4.0.0"
