name: video_player_web_shaka
description: Web platform implementation of video_player and supports hls, dash and mss.
homepage: https://github.com/AR-CADE/video_player_web_shaka
publish_to: 'none' 
version: 1.0.9

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPluginShaka
        fileName: video_player_web_shaka.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.2
  js: ^0.6.7
  video_player_platform_interface: ">=6.2.1 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.4 <=4.0.0"
