name: Flutter CI

on: [push, pull_request]
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: flutter pub get
      -  run: dart fix --apply
      -  run: dart format --set-exit-if-changed .
  
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      -  run: flutter pub get
      -  run: flutter analyze

  build_web:
    name: Build Example web artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cd example && flutter pub get
      - run: cd example && flutter build web --release
      - uses: actions/upload-artifact@v3
        with:
          name: example-web
          path: example/build/web/
 